tasks/blueprint.py
from flask import Blueprint, redirect, render_template, request, abort, jsonify
from flask_login import login_required, current_user
from sqlalchemy import and_, select, union_all

import db_session
from tasks.forms import CreateTaskForm, ChangeStatusForm, EditTaskForm, create_change_status_form, \
    create_edit_task_form, get_statuses
from tasks.models import Task, Status

blueprint = Blueprint('tasks', __name__)
prefix: str = '/tasks'


@blueprint.route('/')
def tasks_by_statuses():
    if current_user.is_authenticated:
        with db_session.create_session() as session:
            statuses: list[Status] = session.scalars(select(Status)).all()
            statuses.sort(key=lambda status: status.id)
            tasks_: dict[int, list[Task | None]] = {
                status.id: session.scalars(
                    select(Task).where(
                        and_(
                            Task.creator_id == current_user.id,
                            Task.status_id == status.id
                        )
                    )
                ).all()
                for status in statuses
            }
            return render_template(prefix + '/tasks_by_statuses.html',
                                   statuses=statuses,
                                   tasks_by_statuses=tasks_)
    return redirect('/')


@blueprint.route('/create', methods=['GET', 'POST'])
@login_required
def create_task():
    form = CreateTaskForm()
    if form.validate_on_submit():
        session = db_session.create_session()
        task = Task()
        task.name = form.name.data
        task.description = form.description.data
        task.creator_id = current_user.get_id()
        if (status := request.args.get('status', None)) is not None:
            task.status_id = status
        session.add(task)
        session.commit()
        return redirect('/tasks')
    return render_template(prefix + '/create.html', form=form, title='Добавить задачу')


@blueprint.route('/<int:task_id>', methods=['GET', 'POST'])
@login_required
def show_task(task_id: int):
    if not current_user.is_authenticated:
        return abort(404)
    with db_session.create_session() as session:
        task: Task = session.query(Task).where(
            and_(current_user.id == Task.creator_id, Task.id == task_id)).first()
        if not task or task.creator_id != current_user.id:
            return abort(404)
        form: ChangeStatusForm = create_change_status_form(task)
        if request.method == 'POST' and form.validate_on_submit():
            new_status_id: int = form.new_status.data
            task.status_id = new_status_id
            session.commit()
            return render_template(prefix + '/show_task.html', task=task, form=form, save=True)
        return render_template(prefix + '/show_task.html', task=task, form=form, save=False)


@blueprint.route('/edit/<int:task_id>', methods=['GET', 'POST'])
@login_required
def edit_task(task_id: int):
    with db_session.create_session() as session:
        task: Task = session.query(Task).where(Task.id == task_id).first()
        if not task or task.creator_id != current_user.id:
            return abort(404)
        form: EditTaskForm = create_edit_task_form(task)
        if request.method == 'GET':
            form.name.data = task.name
            form.description.data = task.description
            return render_template(prefix + '/edit.html', form=form, title='Изменить задачу')
        if form.validate_on_submit:
            task: Task = session.query(Task).where(Task.id == task_id).first()
            task.name = form.name.data
            task.description = form.description.data
            task.status_id = form.new_status.data
            session.commit()
            return redirect(f'/tasks/{task_id}')


@blueprint.route('/delete/<int:task_id>')
@login_required
def delete_task(task_id: int):
    with db_session.create_session() as session:
        task: Task = session.query(Task).where(Task.id == task_id).first()
        if not task or task.creator_id != current_user.id:
            return abort(404)
        session.delete(task)
        session.commit()
        return redirect('/tasks')


@blueprint.route('/get')
@login_required
def get():
    with db_session.create_session() as session:
        tasks: list[Task] = session.query(Task).where(
            and_(current_user.id == Task.creator_id)).all()
        return jsonify(
            {
                'tasks': [task.to_dict(only=('name', 'creator.name', 'description', 'status')) for task in tasks]
            }
        )

templates/basic_template.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>To do App</title>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    {% block links %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/basic.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/home.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/single_task.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/navbar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/color_themes.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/teams.css') }}">
</head>
<body class="w-100 m-0">
{% block content %}{% endblock %}
</body>
</html>

templates/basic_template_with_navbar.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>To do App</title>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    {% block links %}{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/basic.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/home.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/navbar.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/color_themes.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/teams.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/single_task.css') }}">
</head>
<body class="w-100 m-0">
<main class="main-with-navbar">
    {% include 'navbar.html' %}
    <div>
        <section class="page-header">
            <h1>{% block title %}{% endblock %}</h1>
        </section>
        <section class="main-margin">
            {% block content %}{% endblock %}
        </section>
    </div>
</main>
</body>
</html>

templates/index.html
{% extends "basic_template_with_navbar.html" %}

{% block title %}Главная{% endblock %}

{% block content %}

<script>
    window.onload = (event) => {
        document.getElementById('timer-buttons-no-task').style.display = 'none';
        document.getElementById('timer-buttons-on-pause').style.display = 'none';
        document.getElementById('timer-buttons-on-run').style.display = 'none';
    };
</script>

<section class="home-grid">
    <article class="white-filled border-1r">
        <div class="home-grid-title">
            <h6>Profile</h6>
            <a href="{{ url_for('auth.profile') }}"
               class="home-grid-arrow-link light-filled light-filled-on-hover">
                <i class="bi bi-arrow-right"></i>
            </a>
        </div>
        <div class="home-grid-profile">
            <img src="{% if current_user.image %} ../static/uploads/{{ current_user.image }}
                    {% else %} ../static/img/default.png
                    {% endif %}"/>
            <h6>{{ current_user.name }}</h6>
        </div>

    </article>
    <article class="white-filled border-1r">text</article>
    <article class="white-filled border-1r">
        <div class="home-grid-title">
            <h6>Timer</h6>
            <!--                    <a href="{{ url_for('auth.profile') }}" class="home-grid-arrow-link light-filled light-filled-on-hover">-->
            <!--                        <i class="bi bi-arrow-right"></i>-->
            <!--                    </a>-->
        </div>
        <h1 id="timer-display" class="timer-display display-5">--:--:--</h1>

        <div id="timer-buttons-no-task" class="timer-one-button">
            <a href="{{ url_for('tasks.tasks_by_statuses') }}"
               class="timer-link light-filled light-filled-on-hover">
                К задачам
                <i class="bi bi-arrow-right"></i>
            </a>
        </div>

        <div id="timer-buttons-on-run" class="timer-two-buttons">
            <div class="timer-first-button">
                <button id="button-pause" class="timer-button light-filled light-filled-on-hover">
                    <i class="bi bi-pause"></i>
                </button>
            </div>
            <div class="timer-second-button">
                <button id="button-stop1" class="timer-button light-filled light-filled-on-hover">
                    <i class="bi bi-stop-fill"></i>
                </button>
            </div>
        </div>

        <div id="timer-buttons-on-pause" class="timer-two-buttons">
            <div class="timer-first-button">
                <button id="button-play" class="timer-button light-filled light-filled-on-hover">
                    <i class="bi bi-play-fill"></i>
                </button>
            </div>
            <div class="timer-second-button">
                <button id="button-stop2" class="timer-button light-filled light-filled-on-hover">
                    <i class="bi bi-stop-fill"></i>
                </button>
            </div>
        </div>

    </article>
    <article class="white-filled border-1r">text</article>
</section>

<script>
    let item = document.querySelector('#aside-navbar-home');
    item.classList.remove('white-filled-with-hover');
    item.classList.add('dark-filled');
</script>
<script>
    setInterval(function() {
    fetch('/api/timers/check')
               .then(response => response.json())
               .then(data => {
                   if (data.status == 200) {
                       document.getElementById('timer-display').innerHTML = data.data.time;
                       if (data.data.pause) {
                           document.getElementById('timer-buttons-no-task').style.display = 'none';
                           document.getElementById('timer-buttons-on-pause').style.display = 'grid';
                           document.getElementById('timer-buttons-on-run').style.display = 'none';
                       } else {
                           document.getElementById('timer-buttons-no-task').style.display = 'none';
                           document.getElementById('timer-buttons-on-pause').style.display = 'none';
                           document.getElementById('timer-buttons-on-run').style.display = 'grid';
                       }

                   } else {
                       document.getElementById('timer-display').innerHTML = "--:--:--";
                       document.getElementById('timer-buttons-no-task').style.display = 'block';
                       document.getElementById('timer-buttons-on-pause').style.display = 'none';
                       document.getElementById('timer-buttons-on-run').style.display = 'none';
                   }
               });
    }, 200);
</script>
<script>
    function pause() {
        fetch('/api/timers/pause');
    }
    function run() {
        fetch('/api/timers/continue');
    }
    function stop() {
        fetch('/api/timers/terminate');
    }
    document.getElementById('button-play').onclick = run;
    document.getElementById('button-pause').onclick = pause;
    document.getElementById('button-stop1').onclick = stop;
    document.getElementById('button-stop2').onclick = stop;
</script>

{% endblock %}

templates/navbar.html
<aside class="aside-navbar white-filled">
    <nav>
        <a id="aside-navbar-profile" href="{{ url_for('auth.profile') }}" class="navbar-item white-filled-with-hover">
            <i class="bi bi-person-circle"></i>
            <div class="">Profile</div>
        </a>
        <a id="aside-navbar-home" href="{{ url_for('index') }}" class="navbar-item white-filled-with-hover">
            <i class="bi bi-house"></i>
            <div class="">Home</div>
        </a>
        <a id="aside-navbar-teams" href="{{ url_for('teams.user_teams') }}" class="navbar-item white-filled-with-hover">
            <i class="bi bi-people"></i>
            <div class="">Teams</div>
        </a>
        <a id="aside-navbar-tasks" href="{{ url_for('tasks.tasks_by_statuses') }}" class="navbar-item white-filled-with-hover">
            <i class="bi bi-list-task"></i>
            <div class="">Tasks</div>
        </a>
        <a id="aside-navbar-create" href="{{ url_for('tasks.create_task') }}" class="navbar-item white-filled-with-hover">
            <i class="bi bi-plus-circle"></i>
            <div class="">Create task</div>
        </a>
    </nav>
</aside>